# Generated by Django 4.1.5 on 2023-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_post_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_first_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='author_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
