# Generated by Django 4.1.5 on 2023-03-07 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_address_user_last_used_address_and_more'),
        ('order', '0002_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_address', to='authentication.address'),
        ),
    ]
