# Generated by Django 4.1.5 on 2023-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_address_user_last_used_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='test',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
