# Generated by Django 4.1.5 on 2023-06-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_address_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='test',
        ),
    ]
