# Generated by Django 4.1.5 on 2023-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
